# Generated by Django 3.2.6 on 2021-10-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dynamicsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicevolume',
            name='space_allocation_gb',
            field=models.FloatField(),
        ),
    ]
