# Generated by Django 3.2.6 on 2021-08-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210828_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingproject',
            old_name='project_id',
            new_name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
    ]
