# Generated by Django 3.2.6 on 2021-08-31 04:00

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210830_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IDR', 'Indonesian Rupiah'), ('USD', 'US Dollar')], default='IDR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IDR', 'Indonesian Rupiah'), ('USD', 'US Dollar')], default='IDR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='flavorprice',
            name='daily_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flavorprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='floatingipsprice',
            name='daily_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='floatingipsprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.IntegerField(choices=[(1, 'In Progress'), (100, 'Finished')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicefloatingip',
            name='daily_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicefloatingip',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceinstance',
            name='daily_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceinstance',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='daily_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='volumeprice',
            name='daily_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='volumeprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10),
        ),
    ]
