# Generated by Django 3.2.6 on 2021-08-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210831_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
