# Generated by Django 3.2.6 on 2022-02-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_invoice_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='finish_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
