# Generated by Django 3.2.6 on 2021-09-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210901_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicefloatingip',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
