# Generated by Django 3.2.6 on 2021-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210901_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicevolume',
            name='volume_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='volume_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='volume_type_id',
            field=models.CharField(max_length=256),
        ),
    ]
