# Generated by Django 3.2.6 on 2022-10-31 18:01

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavorprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flavorprice',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='flavorprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flavorprice',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='floatingipsprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='floatingipsprice',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='floatingipsprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='floatingipsprice',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='imageprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='imageprice',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='imageprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='imageprice',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoicefloatingip',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicefloatingip',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoicefloatingip',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicefloatingip',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoiceimage',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceimage',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoiceimage',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceimage',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoiceinstance',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceinstance',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoiceinstance',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceinstance',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoicerouter',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicerouter',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoicerouter',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicerouter',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoicesnapshot',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicesnapshot',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoicesnapshot',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesnapshot',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='routerprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='routerprice',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='routerprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='routerprice',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='snapshotprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='snapshotprice',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='snapshotprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='snapshotprice',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='volumeprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='volumeprice',
            name='hourly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='volumeprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='volumeprice',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
