# Generated by Django 3.2.6 on 2022-11-21 15:11

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20221121_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
