LABEL_INSTANCES = "instances"
LABEL_VOLUMES = "volumes"
LABEL_FLOATING_IPS = "floating_ips"
LABEL_ROUTERS = "routers"
LABEL_SNAPSHOTS = "snapshots"
LABEL_IMAGES = "images"

INVOICE_COMPONENT_LABELS = [LABEL_INSTANCES, LABEL_VOLUMES, LABEL_FLOATING_IPS, LABEL_ROUTERS, LABEL_SNAPSHOTS,
                            LABEL_IMAGES]
